# Generated by Django 4.1.2 on 2022-10-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=20)),
                ("type", models.CharField(max_length=30)),
                ("rating", models.CharField(max_length=10)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
