# Generated by Django 4.1.2 on 2022-10-15 10:44

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    location=["/home/sanju/python/anoop-chettan/project/static"]
                ),
                upload_to="",
            ),
        ),
    ]
